import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/layouts/providers/provider/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dokan Admin Dashboard',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={inter.className}
				style={{
					overflowX: 'hidden',
					overflowY: 'hidden',
				}}
			>
				<Provider>{children}</Provider>

				<Toaster />
			</body>
		</html>
	);
}
